services:
  backend:
    image: wizword:latest
    command: sh -c "uvicorn wizword.backend.doc_api:app --host 0.0.0.0 --port 8000"
    env_file: .env
    ports: ["8000:8000"]

  frontend:
    image: wizword:latest
    command: sh -c "./venv/bin/streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0"
    env_file: .env
    environment:
      BACKEND_HINTS_URL: http://backend:8000/generate-hints
    ports: ["8501:8501"]
